# yaml
app:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      vehicle: vehicle-events

spring:
  kafka:
    bootstrap-servers: ${app.kafka.bootstrap-servers}
    consumer:
      group-id: garage-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
